name: MultiServerPortals
version: 1.0
main: com.example.multiserverportals.MultiServerPortals
api-version: 1.17
author: appipinopi
description: MultiServerPortals plugin allows players to teleport between servers using portals.
commands:
  move:
    description: Teleports the player to the specified server.
    usage: /move <server name> <username>
  sp:
    description: Enable or disable transfer of items, XP, armor, or ender chest contents.
    usage: /sp <server name> <i|item|x|xp|ar|armor|e|enderchest|g|go> <true|false>
  savarproperties:
    description: Alias for /sp command.
    usage: /savarproperties <server name> <i|item|x|xp|ar|armor|e|enderchest|g|go> <true|false>
  cos:
    description: Registers a new server.
    usage: /cos <IP address> <port> <server name>
  connectingservers:
    description: Alias for /cos command.
    usage: /connectingservers <IP address> <port> <server name>
