default-settings:
  cos-register-message: "Server %server% registered with IP %ip% and port %port% for road %road%."
  move-message: "Player %player% moved to server %server%."
  sp-enable-message: "Transfer option %option% enabled for server %from%."
  sp-disable-message: "Transfer option %option% disabled for server %from%."
  whitelist-enable-message: "Player %player% is now whitelisted for road %road%."
  whitelist-disable-message: "Player %player% is no longer whitelisted for road %road%."
transfer-options:
  # Example:
  # myServer:
  #   item: true
  #   xp: false
whitelist:
  # Example:
  # roadName:
  #   playerName: true
