name: MultiServerPortals
version: 1.0
main: com.example.multiserverportals.MultiServerPortals
api-version: 1.16
commands:
  move:
    description: "指定されたサーバーにプレイヤーを移動します"
    usage: "/move <server name> <username>"
  sp:
    description: "特定のサーバーのアイテム、XP、防具、エンダーチェスト、ホワイトリストの転送オプションを有効または無効にします"
    usage: "/sp <server name> <option> <true|false>"
  savarproperties:
    description: "/sp の別名です"
    usage: "/savarproperties <server name> <option> <true|false>"
    aliases: [sp]
  cos:
    description: "新しいサーバーを登録します"
    usage: "/cos <IP address> <port> <server name>"
  connectingservers:
    description: "/cos の別名です"
    usage: "/connectingservers <IP address> <port> <server name>"
    aliases: [cos]
