name: MultiServerPortals
main: com.example.multiserverportals.PaperMain
version: 1.0.0
api-version: 1.16
commands:
  move:
    description: Move player to specified server
  sp:
    description: Set server properties
  cos:
    description: Register a new server
  savarproperties:
    description: Alias for /sp
    aliases: [sp]
  connectingservers:
    description: Alias for /cos
    aliases: [cos]
  wh:
    description: Whitelist a player for a specific road
  whitelist:
    description: Alias for /wh
    aliases: [wh]
